### PR TITLE
added venv, python3, pip3

### PR DESCRIPTION
**Pull request by ameeracadam**
Need to create venv within build_docker.sh

### CODE REVIEW

**Comment by jaabberwocky** [comment]
Eh you are just activating the venv in your own environment? You should have done that right at the start. Can you `source .venv/bin/activate` before running the script then ensure it runs?

**Comment by jaabberwocky** [comment]
To clarify, I mean without the `python3 -m venv .venv` and `source .venv/bin/activate` lines in the script.

**Comment by ameeracadam** [comment]
hmm... just now when I tried it threw attribute error even in venv.. don't know why now suddenly even when commenting out can..

**Comment by ameeracadam** [comment]
I guess can comment it our in the script then

**Comment by jaabberwocky** [comment]
Because previously you didn't activate your `.venv` environment? That's the only explanation why that would work.

**Comment by jaabberwocky** [comment]
You confirm the script works with the two lines you commented out?

**Comment by ameeracadam** [comment]
yeah confirm

**Pull request merged**
